# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 105c60f2881cf3e9b81198e34cd5994c1a6500af15c8683911579df9698f626fbbfd17b766bc24737bc4df12709e811ce5076875454de696351f65c2626a3e49

test:
  secret_key_base: 8b1a3dfb6eac6ba35ffebec4ef75e4b8c4f9659f825af2726b993f64b4b69b89b76a9d7c978cc2e2832745b0922b7d058e89f9918b0becf6afdab0c35a42fe0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
